accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views #built-in login and logout passwordchange view and what-not
from . import views
from django.core.urlresolvers import reverse_lazy


# TEMPLATE TAG
app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^update/(?P<username>[\w\-]+)/$', views.UserUpdateView.as_view(), name='profile_update'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
        subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset/<uidb64>/<token>/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),

    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

play/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


# TEMPLATE TAG
app_name = 'play'

urlpatterns = [
    url(r'^$', views.PlayTemplateView.as_view(), name='play'),
    url(r'^game/(?P<slug>[\w\-]+)/$', views.PlayDetailView.as_view(), name='playdetail'),
]

store/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    url(r'^add/$', views.AddGame.as_view(), name='addgame'),
    url(r'^game/(?P<slug>[\w\-]+)/$',views.GameDetailView.as_view(), name='gamedetail'),
    url(r'^delete/(?P<slug>[\w\-]+)/$', views.GameDeleteView.as_view(), name='delete'),
    url(r'^buy/(?P<slug>[\w\-]+)/$', views.BuyView.as_view(), name='buy'),
    url(r'^buy/paymentsuccess/*', views.PaymentSuccessTemplateView.as_view(), name='pay_success'),
    url(r'^buy/paymentstopped/*', views.PaymentCancelTemplateView.as_view(), name='pay_cancel'),
    url(r'^update/(?P<slug>[\w\-]+)/$', views.GameUpdateView.as_view(), name='update'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.ProfileListView.as_view(), name='profile'),

    url(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(template_name='store/password_change_form.html'),
        name='password_change'),

    url(r'^password_change/done/$',
       auth_views.PasswordChangeDoneView.as_view(template_name='store/password_change_done.html'),
       name='password_change_done'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePageListView.as_view(), name='home'),
    url(r'^', include('store.urls', namespace='store')),
    url(r'^', include('django.contrib.auth.urls')), #connect built-in authorization
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')), #connect built-in authorization
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^play/', include('play.urls',namespace='play')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.utils.text import slugify
from django import template
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.conf import settings
User = settings.AUTH_USER_MODEL

class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def to_json(self):
        json = {'id': self.id, 'name': self.name}
        return json

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['name']

class Game(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    developer = models.ForeignKey(User, related_name='game_developed_by', null=True)
    owners = models.ManyToManyField(User, related_name='game_owned_by')
    genre = models.ForeignKey(Genre, related_name='game_genre')
    description = models.TextField(blank=True, default='')
    coverpicture = models.ImageField(upload_to='cover_pics', blank=True)
    url = models.URLField(null=False, blank=False, unique=True)
    price = models.DecimalField(null=False, blank=False, max_digits=5,
                                decimal_places=2,validators=[MinValueValidator(Decimal('0.00'))])
    games_sold = models.PositiveIntegerField(default = 0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('store:gamedetail', kwargs={'slug':self.slug})

    def __str__(self):
        return self.name

store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from store.models import Game, Genre
from django.http import Http404
from .import forms
from django.conf import settings
User = settings.AUTH_USER_MODEL
# from braces.views import SelectRelatedMixin #this is required for models foreignKeys
import time
from hashlib import md5

class AddGame(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, generic.CreateView):
    fields = ('name','genre','description', 'url', 'price', 'coverpicture')
    model = Game
    success_message = "%(name)s has been created"

    def test_func(self):
        return self.request.user.is_developer

    # before committing the form save the ownership changes to database
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.developer = self.request.user #the developer of the game is the one who submits the form
        self.object.save()
        self.object.owners.add(self.request.user) #add the user to owners of the game
        self.object.save()
        self.request.user.my_games.add(self.object)
        self.request.user.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


class GameUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, generic.UpdateView):
    model = Game
    fields = ['name', 'price', 'description', 'genre', 'coverpicture']
    template_name_suffix = '_update_form'
    raise_exception = True
    success_message = "%(name)s has been updated"

    #protect the view from users that arent the developer of the game
    def test_func(self):
        if self.get_object().developer == self.request.user:
            return True
        return False

    def get_success_url(self):
        return reverse('home')

class GameDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Game
    raise_exception = True

    # user needs to be the developer of the game
    def test_func(self):
        if self.get_object().developer == self.request.user:
            return True
        return False

    def get_success_url(self):
        return reverse('home')

class GameDetailView(generic.DetailView):
    model = Game
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BuyView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = Game
    template_name = 'store/game_buy.html'
    fields = []
    raise_exception = True

    # protect the view from users that don't have permission to get there
    def test_func(self):
        # user already owns the game
        if self.get_object().developer == self.request.user:
            return False
        # user has bought the game already
        elif self.get_object().owners.all().filter(username__iexact = self.request.user.username).exists():
            return False
        # other authenticated users have permission to buy the game if their logged in
        return True

    # payment data handling in the view according to the instructions
    def get_context_data(self, *args, **kwargs):
        pid = self.request.user.username + "_" + str(self.get_object().id) + "_" + str(time.time())
        amount = self.get_object().price
        sid = 'wsdokumakeotso'
        secret_key = '470a3830bed492b6291a26d65cd2b0cb'
        checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
        checksumstr2 = "pid=%s&sid=%s&amount=%s&token=%s" % (pid, sid, amount, secret_key)
        m = md5(checksumstr.encode("ascii"))
        checksum = m.hexdigest()

        context = super(BuyView, self).get_context_data(*args, **kwargs)
        context['game'] = self.get_object()
        context['User'] = self.request.user
        context['amount'] = amount
        context['pid'] = pid
        context['sid'] = sid
        context['secret_key'] = secret_key
        context['success_url'] = 'https://indiegames.herokuapp.com/buy/paymentsuccess'
        context['error_url'] = 'https://indiegames.herokuapp.com/buy/paymentstopped'
        context['cancel_url'] = 'https://indiegames.herokuapp.com/buy/paymentstopped'
        context['checksumstr'] = checksumstr
        context['checksumstr2'] = checksumstr2
        context['checksum'] = checksum

        # print(context)
        return context

class PaymentSuccessTemplateView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    template_name = 'store/payment_success.html'
    raise_exception = True

    def test_func(self):
        pid = self.request.GET['pid'].split('_')
        game_id = int(pid[1])
        game = get_object_or_404(Game, id=game_id)
        print(game.owners.all())

        # user is trying to use someboy elses payment succesful URL
        if self.request.user.username != pid[0]:
            return False

        #user already owns the game
        if game.owners.all().filter(username__iexact=self.request.user.username).exists():
            return False

        # now we can do the database changes
        self.request.user.my_games.add(game)
        game.owners.add(self.request.user)
        game.games_sold += 1
        game.save()

        return True

    def get_context_data(self, *args, **kwargs):
        pid = self.request.GET['pid'].split('_')
        game_id = int(pid[1])
        game = get_object_or_404(Game, id=game_id)
        context = super(PaymentSuccessTemplateView, self).get_context_data(*args, **kwargs)
        context['game']=game
        return context


class PaymentCancelTemplateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'store/payment_cancel.html'

    def get_context_data(self, *args, **kwargs):
        result = self.request.GET['result']
        checksum = self.request.GET['checksum']
        context = super(PaymentCancelTemplateView, self).get_context_data(*args, **kwargs)
        if result == 'cancel':
            context['payment_cancel'] = result
        elif result == 'error':
            context['payment_error'] = result
        print(context)
        return context

class ProfileListView(LoginRequiredMixin, generic.ListView):
    model = Game
    template_name = 'store/profile_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileListView, self).get_context_data(*args, **kwargs)
        return context

store/templates/store/game_buy.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
{% if user.is_authenticated %}
<br>
<div class="row d-flex justify-content-center">
  <h1>You are about to buy the following:</h1>
</div>
<br>
<div class="row d-flex justify-content-center">
  <div class="form-group">
    <form action="http://payments.webcourse.niksula.hut.fi/pay/" method="POST">
      <input type="hidden" name="pid" value="{{pid}}" />
      <input type="hidden" name="sid" value="{{sid}}" />
      <input type="hidden" name="success_url" value={{success_url}} />
      <input type="hidden" name="cancel_url"  value={{cancel_url}} />
      <input type="hidden" name="error_url"   value={{error_url}} />
      <input type="hidden" name="checksum"    value={{checksum}} />
      <input type="hidden" name="amount" value={{amount}} />
      <input type="hidden" name="checksumstr" value={{checksumstr}} />
      <input type="hidden" name="dev" value="error">

      <div class="row d-flex justify-content-center">
        <label for="id_amount"><h1>Game: {{Game.name}}</h1></label>
      </div>

      <div class="row d-flex justify-content-center">
        <label for="id_amount"><h1>Price {{amount}} $</h1></label>
      </div>

      <br>
      <div class="row-padded d-flex justify-content-center">
        <input type="submit" class="btn btn-outline-success btn-block" value="Purchase"/>
      </div>
    </form>
  </div>
</div>
{% endif %}
{% endblock content %}

store/templates/store/game_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<br>
<div class="container d-flex justify-content-center">
 <form caction="" method="post">
   {% csrf_token %}
   <h1>Are You sure you want to delete your game: "{{ object.name }}" ?</h1><br>
   <input type="submit" class="btn btn-danger btn-lg btn-block" value="Confirm">
 </form>
</div>
{% endblock content %}

store/templates/store/game_detail.html
{% extends "base.html" %}
{% block content  %}
    <br>
    <div class="row d-flex justify-content-center">
      <h1>{{ game.name }}</h1>
      <div class="game-description container-fluid d-flex justify-content-center">
        <p>{{ game.description }}</p>
      </div>
      <div class="game-description container-fluid d-flex justify-content-center">
        <p>Price: {{ game.price }}$</p>
      </div>
    </div>
    <br>
      <!-- Tähän pelin kansikuva  -->
      {% if user.is_authenticated and user == game.developer %}
      <div class="container">
        <div class="d-flex justify-content-center">
          <a href="{% url 'play:playdetail' slug=game.slug %}" class="btn btn-success btn-lg btn-block">Play</a>
        </div>
        <br>
        <div class="d-flex justify-content-center">
          <a href="{% url 'store:update' slug=game.slug %}" class="btn btn-warning btn-lg btn-block">Update</a>
        </div>
        <br>
        <div class="d-flex justify-content-center">
          <a href="{% url 'store:delete' slug=game.slug %}" class="btn btn-danger btn-lg btn-block">Delete</a>
        </div>
      </div>

      {% elif user.is_authenticated and user in game.owners.all  %}
      <div class="container">
        <div class="d-flex justify-content-center">
          <a class="btn btn-success btn-lg btn-block" href="{% url 'play:playdetail' slug=game.slug %}">Play</a>
        </div>
      </div>


      {% elif user.is_authenticated and user not in game.owners.all %}
      <div class="container">
        <div class="d-flex justify-content-center">
          <a href="{% url 'store:buy' slug=game.slug  %}" class="btn btn-primary btn-lg btn-block">Buy</a>
        </div>
      </div>

      {% else %}
      <div class="col-md-12 d-flex justify-content-center">
        <p>You need to have an user account to buy this game</p>
        <p>{{ user.profile.my_games }}</p>
      </div>
      <div class="container d-flex justify-content-center">
        <a href= "{% url 'accounts:signup' %}" class="btn btn-outline-primary btn-lg btn-block">Sign Up</a>
      </div>
      <br>
      <div class="container d-flex justify-content-center">
        <a href= "{% url 'accounts:login' %}" class="btn btn-outline-primary btn-lg btn-block">Login</a>
      </div>
      {% endif %}
{% endblock content  %}

store/templates/store/game_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<br>
<div class="col-md-6 justify-content-center mx-auto">
  <h4>Add a new Game!</h4>
  <form class="" action="{% url 'store:addgame' %}" method="post" id="gameform">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-lg" value="Add to store">
  </form>
</div>

{% endblock content %}

store/templates/store/game_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
 <div class="container">
   <div class="row">
     <div class="col-md-12">
      <div class="d-flex justify-content-center mx-auto">
        <h1>Shop for indie Games</h1>
      </div>
      <br>
      <div class="row">
        <div class="col-lg-12 d-flex align-items-stretch">
          <div class="list-games col-md-12">
            <ul class="list-unstyled">
              {% for game in object_list %}
              <li>
                <div class="card mb-4 border-dark" style="box-shadow: 3px 3px 9px;">
                  {% if game.coverpicture %}
                   <img src="{% get_media_prefix %}{{ game.coverpicture }}">
                  {% else %}
                   <img src="{% get_media_prefix %}cover_pics/gamepic2.png">
                  {% endif %}

                  <div class="content d-flex justify-content-center">
                    <a class="list-games-item" href="{% url 'store:gamedetail' slug=game.slug %}">
                      <h3 class='title list-games-item-title'>{{game.name}}</h3>
                      <!-- Tähän pelin kansikuva -->
                    </a>
                  </div>
                  {% if user == game.developer %}
                   <div class="d-flex justify-content-center" style="font-size: 20px">self-made</div>
                  {% elif user in game.owners.all %}
                   <div class="d-flex justify-content-center" style="font-size: 20px">bought</div>
                  {% else %}
                   <div class="d-flex justify-content-center" style="font-size: 20px">buyable</div>
                  {% endif %}
                </div>
              </li>
              {% empty %}
                <p>No Games Here Yet!</p>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
     </div>
     <div class="col-md-12">
       {% if user.is_authenticated and user.is_developer %}
       <div class="d-flex justify-content-center">
         <a href="{% url 'store:addgame' %}" class="btn btn-block btn-warning">Add a New Game</a>
       </div>
       {% endif %}
     </div>
   </div>
 </div>
 <br><br>
</div>
{% endblock content %}

store/templates/store/game_update_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
  <br>
  <div class="col-md-6 justify-content-center mx-auto">
    <form action="" method="post" id="updateform" >
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-lg btn-warning" type="submit" value="Update Game Info" />
    </form>
  </div>
{% endblock content %}

store/templates/store/password_change_done.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
  <h3>Your new password has been set. Now you can access your account using your new password.</h3>
</div>
{% endblock content %}

store/templates/store/password_change_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<br>
<div class="container">
  <h1>Please enter your old password once and your new password twice</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn btn-outline-secondary" value="Change password">
  </form>
</div>
{% endblock content %}

store/templates/store/payment_cancel.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container">
    <div class="col-md-12 row">
      <div class="d-flex justify-content-center mx-auto">
        <h3>{% if payment_cancel %}Payment was {{payment_cancel}}led {%elif payment_error%} There was an {{payment_error}} in the payment {% endif %}</h3>
      </div>
    </div>
</div>
{% endblock content %}

store/templates/store/payment_success.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container">
    <div class="col-md-12 row">
      <div class="d-flex justify-content-center mx-auto">
        <h4>Thank you for buying the game!</h4>
      </div>
    </div>
    <br>
    <div class="col-md-12 row-padded">
      <div class="d-flex justify-content-center">
        <a href="{% url 'play:playdetail' slug=game.slug %}" class="btn btn-block btn-success">Try out the new game</a> <!--Needs proper linking still -->
      </div>
    </div>
</div>
{% endblock content %}

store/templates/store/profile_list.html
{% extends "base.html" %}
{% block content %}

<br>
<div class="container" style="border:5px solid #6c757d;">
  <div class="d-flex flex-column">
    <div class="p-3">
      <div class ="panel-group">
        <div class = "panel panel-default">
          <div class="panel-heading" style="border:2px solid #6c757d;">
            <h2 class="text-center">User Details: </h2>
            <p class="text-center"> Username: {{ user.username }} </p>
            <p class="text-center"> Developer status: {% if user.is_developer %} Yes {% else %} No {% endif %} </p>
            <p class="text-center">Email: {{ user.email }} </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container d-flex justify-content-center mx-auto">
      <a href="{% url 'store:password_change' %}" class="btn btn-block btn-outline-secondary" style="border:2px solid; border-radius:0">Change Password</a>
    </div>
    <br>

    <div class="container d-flex justify-content-center mx-auto">
      <a href="{% url 'accounts:profile_update' username=user.username %}" class="btn btn-block btn-outline-secondary" style="border:2px solid; border-radius:0">Update profile</a>
    </div>

    <div class="p-3">
      <div class ="panel-group">
        <div class = "panel panel-default">
          <div class="panel-heading" style="border:2px solid #6c757d;">
            <h2 class="text-center"> Personal Library: </h2>


            <div class="table-responsive">
              <table class ="table">
                <tr class="text-center">
                  <th> Title </th>
                  <th> Genre </th>
                  <th> Price </th>
                </tr>
                {% for game in user.my_games.all  %}

                <tr class="text-center">
                  <td style="width:33%;"> <a href="{% url 'store:gamedetail' slug=game.slug %}"> {{ game.name }} </a> </td>
                  <td style="width:33%;">{{ game.genre }} </td>
                  <td style="width:33%;">{{ game.price }} $ </td>
                </tr>
                {% empty %}
                <p class="text-center">No games in your library. Purchase some <a href="{% url 'home' %}"> here!</a></p>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% if user.is_developer %}
      <div class="p-3">
        <div class ="panel-group">
          <div class = "panel panel-default" >
            <div class="panel-heading " style="border:2px solid #6c757d;">
              <h2 class="text-center"> Submitted Games </h2>
              <div class=" d-flex justify-content-center">
                {% for game in game_list %}
                  {% if user == game.developer %}
                    <div class="table-responsive">
                      <table class ="table">
                        <tr class="text-center">
                          <th> Title </th>
                          <th> Units Sold </th>
                        </tr>


                        <tr class ="text-center">
                          <td style="width:50%;"> <a href="{% url 'store:gamedetail' slug=game.slug %}"> {{ game.name }} </a> </td>
                          <td style="width:50%;">{{ game.games_sold }} </td>
                        </tr>
                      </table>
                    </div>
                  {% endif %}
                  {% empty %}
                    <p>You have not submitted any games to the store</p>
                {% endfor %}
              </div>
              <div class="d-flex justify-content-center mx-auto">
                <a href="{% url 'store:addgame' %}" class="d-block btn btn-block btn-warning" style="border-radius:0;">Add a New Game</a>
              </div>
              <br>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
  </div>
</div>



</div>
<br><br>






{% endblock content %}

store/templates/store/store.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1>Shop for shit Games</h1>
        <div class="list-games">
          {% if game %}
            {% for game in object_list %}
              <a class="list-games-item" href="{url 'store:gamedetail'}">
                <h3 class='title list-games-item-title'>{{game.name}}</h3>
                <!-- Tähän pelin kansikuva -->
              </a>
            {% endfor %}
          {% else %}
            <p>No Games Here Yet!</p>
          {% endif %}
        </div>
      </div>
      <div class="col-md-4">
        {% if user.is_authenticated and user in game.owners.all %}
          <a href="{% url store:addgame %}" class="btn btn-md btn-warning">Add a New Game</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}