accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views #built-in login and logout passwordchange view and what-not
from . import views
from django.core.urlresolvers import reverse_lazy


# TEMPLATE TAG
app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^update/(?P<username>[\w\-]+)/$', views.UserUpdateView.as_view(), name='profile_update'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
        subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset/<uidb64>/<token>/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),

    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

play/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


# TEMPLATE TAG
app_name = 'play'

urlpatterns = [
    url(r'^$', views.PlayTemplateView.as_view(), name='play'),
    url(r'^game/(?P<slug>[\w\-]+)/$', views.PlayDetailView.as_view(), name='playdetail'),
]

store/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    url(r'^add/$', views.AddGame.as_view(), name='addgame'),
    url(r'^game/(?P<slug>[\w\-]+)/$',views.GameDetailView.as_view(), name='gamedetail'),
    url(r'^delete/(?P<slug>[\w\-]+)/$', views.GameDeleteView.as_view(), name='delete'),
    url(r'^buy/(?P<slug>[\w\-]+)/$', views.BuyView.as_view(), name='buy'),
    url(r'^buy/paymentsuccess/*', views.PaymentSuccessTemplateView.as_view(), name='pay_success'),
    url(r'^buy/paymentstopped/*', views.PaymentCancelTemplateView.as_view(), name='pay_cancel'),
    url(r'^update/(?P<slug>[\w\-]+)/$', views.GameUpdateView.as_view(), name='update'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.ProfileListView.as_view(), name='profile'),

    url(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(template_name='store/password_change_form.html'),
        name='password_change'),

    url(r'^password_change/done/$',
       auth_views.PasswordChangeDoneView.as_view(template_name='store/password_change_done.html'),
       name='password_change_done'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePageListView.as_view(), name='home'),
    url(r'^', include('store.urls', namespace='store')),
    url(r'^', include('django.contrib.auth.urls')), #connect built-in authorization
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')), #connect built-in authorization
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^play/', include('play.urls',namespace='play')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Gameshop</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/master.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark" role='navigation'>
      <div class="container">
        <a class="navbar-brand nav-item nav-link active" href="{% url 'home' %}">STORE</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#mainNav">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="mainNav">
          <ul class="nav navbar-nav navbar-right ml-auto">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                  {% if user.is_developer %}
                    <span class="navbar-text" style="margin-right:25px;"> Logged in as {{user.username}} (developer)</span>
                  {% else %}
                    <span class="navbar-text" style="margin-right:25px;"> Logged in as {{user.username}}</span>
                  {% endif %}
                    <a class="nav-item nav-link" href="{% url 'store:profile' username=user.username %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'play:play' %}">Stats</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                  <span class="navbar-text" style="margin-right:25px;">You haven't logged in!</span>
                  <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                {% endif %}
            </div>
          </ul>
        </div>

      </div>
    </nav>

    <br>
      {% if messages %}
        <div class="d-flex justify-content-center mx-auto">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true" >&times;</span>
              <span class="sr-only">Close</span>
            </button>
            {% for message in messages %}
              {{message}}
            {% endfor %}
          </div>
        </div>
      {% endif %}

    {% block content %}

    {% endblock content %}
  </body>
</html>

templates/thanks.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container">
  <div class="col-md-12">
    <div class="row">
      <div class="d-flex justify-content-center mx-auto">
        <h4>Thank you, hope to see you back soon!</h4>
      </div>
    </div>
  </div>
{% endblock content %}