play/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


# TEMPLATE TAG
app_name = 'play'

urlpatterns = [
    url(r'^$', views.PlayTemplateView.as_view(), name='play'),
    url(r'^game/(?P<slug>[\w\-]+)/$', views.PlayDetailView.as_view(), name='playdetail'),
]

store/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    url(r'^add/$', views.AddGame.as_view(), name='addgame'),
    url(r'^game/(?P<slug>[\w\-]+)/$',views.GameDetailView.as_view(), name='gamedetail'),
    url(r'^delete/(?P<slug>[\w\-]+)/$', views.GameDeleteView.as_view(), name='delete'),
    url(r'^buy/(?P<slug>[\w\-]+)/$', views.BuyView.as_view(), name='buy'),
    url(r'^buy/paymentsuccess/*', views.PaymentSuccessTemplateView.as_view(), name='pay_success'),
    url(r'^buy/paymentstopped/*', views.PaymentCancelTemplateView.as_view(), name='pay_cancel'),
    url(r'^update/(?P<slug>[\w\-]+)/$', views.GameUpdateView.as_view(), name='update'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.ProfileListView.as_view(), name='profile'),

    url(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(template_name='store/password_change_form.html'),
        name='password_change'),

    url(r'^password_change/done/$',
       auth_views.PasswordChangeDoneView.as_view(template_name='store/password_change_done.html'),
       name='password_change_done'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePageListView.as_view(), name='home'),
    url(r'^', include('store.urls', namespace='store')),
    url(r'^', include('django.contrib.auth.urls')), #connect built-in authorization
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')), #connect built-in authorization
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^play/', include('play.urls',namespace='play')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

play/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from store.models import Game
from django.conf import settings
User = settings.AUTH_USER_MODEL

class Score(models.Model):
    game = models.ForeignKey(Game, related_name="high_scores")
    player = models.ForeignKey(User, related_name="user_scores")
    score = models.PositiveIntegerField()
    date = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return self.game.name + ", " + str(self.score)

    class Meta:
        ordering = ['score']

class GameSave(models.Model):
    game = models.ForeignKey(Game)
    user = models.ForeignKey(User)
    saveData = models.TextField(null=True, blank=True)
    saveDate = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.game.name + ", " + self.user.username

    class Meta:
        unique_together = ("game", "user")

play/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from store.models import Game, Genre
from django.http import Http404, HttpResponseRedirect, HttpResponse
from .import forms
from django.conf import settings
from play.models import Score, GameSave
User = settings.AUTH_USER_MODEL


class PlayTemplateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'play/play.html'

    # context dict
    def get_context_data(self, *args, **kwargs):
        user=self.request.user

        # create a 2d-list of personal gamescores. One list for personal scores per game.
        personal_scores = user.user_scores.all().order_by('game')
        if personal_scores.exists():
            personal_scores_by_game_list = []
            personal_scores_per_game = []
            previous_game = [personal_scores.first().game]

            for score in personal_scores:

                if score.game == previous_game[0]:
                    personal_scores_per_game.append(score)
                elif score.game != previous_game[0]:
                    sorted_scores = sorted(personal_scores_per_game, key=lambda score: -score.score)
                    personal_scores_by_game_list.append(sorted_scores)
                    personal_scores_per_game=[]
                    previous_game[0]=score.game

            sorted_scores=sorted(personal_scores_per_game, key=lambda score: -score.score)
            personal_scores_by_game_list.append(sorted_scores)
        else:
            personal_scores_by_game_list = []

        # create context dict
        games=self.request.user.my_games.all()
        context = super(PlayTemplateView, self).get_context_data(*args, **kwargs)
        context['user']=user
        context['games']=games
        context['personalscores']=personal_scores_by_game_list
        print(context)
        return context

class PlayDetailView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Game
    template_name = 'play/play_detail.html'
    raise_exception = True  # raises exeption if user doesnt pass test function

    # let's create a post method for the view so it supports POST-requests
    def post(self, *args, **kwargs):
        if self.request.method == 'POST':

            # SCORE SUBMITTING FROM GAME TO SERVICE
            if self.request.POST['type'] == 'SCORE':
              score = int(self.request.POST['score'])
              game = int(self.request.POST['game'])
              user = int(self.request.POST['user'])
              newscore = Score(game_id=game, player_id=user, score=score)
              newscore.save()
              return HttpResponse("Score saved successfully!")

            # GAME SAVING FROM GAME TO SERVICE
            elif self.request.POST['type'] == 'SAVE':
              data = self.request.POST['data']
              game = int(self.request.POST['game'])
              user = int(self.request.POST['user'])

              if GameSave.objects.filter(game_id=game, user_id=user).exists():
                  GameSave.objects.filter(game_id=game, user_id=user).update(saveData=data)
                  return HttpResponse("save updated successfully!")

              else:
                  newsave = GameSave(game_id=game, user_id=user, saveData=data)
                  newsave.save()
                  return HttpResponse("file saved successfully!")

            # LOAD DATA FROM SERVER TO THE GAME
            elif self.request.POST['type'] == 'LOAD':
                game = int(self.request.POST['game'])
                user = int(self.request.POST['user'])

                if GameSave.objects.filter(game_id=game, user_id=user).exists():
                    result = get_object_or_404(GameSave, game_id=game, user_id=user)
                    print(result.saveData)
                    return HttpResponse(result.saveData)
                else:
                    return HttpResponse("")
    # permissions
    def test_func(self, *args, **kwargs):
        # user owns the game
        game = self.get_object()
        if game.owners.all().filter(username__iexact = self.request.user.username).exists():
            return True
        else:
            return False

    # context dict
    def get_context_data(self, *args, **kwargs):

        context = super(PlayDetailView, self).get_context_data(*args, **kwargs)
        context['user'] = self.request.user
        context['highscores'] = self.object.high_scores.order_by("-score")[:5]

        print(context)
        return context

play/templates/play/play.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
  <div class="d-flex justify-content-center mx-auto">
    <h1>Personal gaming stats:</h1>
  </div>
</div>


<br>
<div class="container" style="border:5px solid #6c757d;">
  <div class="d-flex flex-column">


    <div class="p-3">
      <div class ="panel-group">
        <div class = "panel panel-default">

          <h2 class="text-center"> Personal Library: </h2>

          <div class="table-responsive">
            <table class ="table">
              <tr class="text-center">
                <th> Games </th>
                <th> Genre </th>
                <th> Price </th>
              </tr>
              {% for game in games  %}

              <tr class="text-center">
                <td style="width:33%;"> <a href="{% url 'store:gamedetail' slug=game.slug %}"> {{ game.name }} </a> </td>
                <td style="width:33%;">{{ game.genre }} </td>
                <td style="width:33%;">{{ game.price }} $ </td>
              </tr>
              {% empty %}
              <p class="text-center">No games in your library. Purchase some <a href="{% url 'home' %}"> here!</a></p>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% for scorelist in personalscores %}
<br>
<div class="container" style="border:5px solid #6c757d;">
  <div class="d-flex flex-column">
    <div class="p-3">
      <div class ="panel-group">
        <div class = "panel panel-default">

          <h2 class="text-center">Highscores:</h2>
          <div class="table-responsive">
            <table class ="table">
              <tr class="text-center">
                <th> Game </th>
                <th> Date </th>
                <th> Score </th>
              </tr>
              {% for score in scorelist|slice:":5" %}
                <tr class="text-center">
                  <td style="width:33%;">{{ score.game }} </td>
                  <td style="width:33%;">{{ score.date }} </td>
                  <td style="width:33%;">{{ score.score }} </td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endfor %}

<br><br>
</div>





<!-- <div class="container">
<div id="anchor" class="margined">
<div id="iframeContainer" class="tile">
<iframe id="iframeGame" src="https://www.w3schools.com"></iframe>
</div>
</div>
</div> -->

{% endblock content %}

play/templates/play/play_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>
<div class="container">
  <div class="d-flex justify-content-center">
    <h1>You're playing: {{game}}</h1>
  </div>
  <div class="d-flex justify-content-center">
    <p>{{game.description}}<p>
  </div>
</div>
<div class="container">
  <div class="d-flex justify-content-center">
    <iframe id="iframe1" src="{{game.url}}"></iframe>
  </div>
</div>
<br>
<div class="container">
  <div class="d-flex justify-content-center">
    <h1>Highscores:</h1>
  </div>
</div>
<div class="container" style="border:5px solid #6c757d;">
  <div class="table-responsive">
    <table class ="table">
      <tr class="text-center">
        <th> Player </th>
        <th> Date </th>
        <th> Score </th>
      </tr>
      {% for score in highscores %}
        <tr class="text-center">
          <td class="player" style="width:33%;"> {{ score.player }} </a> </td>
          <td class="date" style="width:33%;"> {{ score.date }} </td>
          <td class="scores" style="width:33%;"> {{ score.score }} </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
<br><br>


<script>

$(document).ready(function() {
// =============================================================
// CSRF code from https://docs.djangoproject.com/en/2.0/ref/csrf/
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');

  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
// ================================================================

  var ifr = document.querySelector('#iframe1').contentWindow;
  var user = {{user.id}};
  var game = {{game.id}};
  var url =  '{{game.url}}';
  //listening for messages from the game
  $(window).on('message', function(evt){

  		var event = evt.originalEvent;
  		var url_str = this.location.pathname //'{{request.build_absolute_uri}}';

  		switch (event.data.messageType){
        case "SETTING":
          console.log(event);
          var width = parseInt(event.data.options.width);
          var height = parseInt(event.data.options.height);
          $('#iframe1').css('width',width);
          $('#iframe1').css('height',height);
          break;

  			case "SCORE":
          console.log(event);
          console.log(this.location.pathname);
  				$.post(url_str,
    				{
    					type: "SCORE",
    					user: user,
    					game: game,
    					score: event.data.score
    				},
			      function(data){
				      var message = {messageType: "MESSAGE", message: data};
              console.log(message);
				      ifr.postMessage(message, url);
            },
          );
  				break;

  			case "SAVE":
          console.log(event);
  				$.post(url_str,
    				{
    					type: "SAVE",
    					user: user,
    					game: game,
    					data: JSON.stringify(event.data.gameState)
    				},
    				function(data,status){
    					var message = {messageType: "MESSAGE", message: data};
              console.log(message);
    					ifr.postMessage(message, url);
       			}
          );
  				break;

  			case "LOAD_REQUEST":
          console.log(event);
  				$.post(url_str,
    				{
    					type: "LOAD",
    					user: user,
    					game: game
    				},
    				function(data, status){
              var message;
    					if(data.length > 1){
    						var obj = JSON.parse(data);
       					message = {messageType: "LOAD", gameState: obj};
                console.log(message);
    					}else{
      					message = {messageType: "ERROR", info: "No file to be loaded."};
                console.log(message);
      				}
    					ifr.postMessage(message, url);
       			}
          );
  				break;
        }

  	});
//===========================================================================
});
</script>

{% endblock content %}